### ISSUE TITLE
GetCPInfo doesn't return current alert text

### ISSUE THREAD

**Issue by JeLuF** [holyrics/API-Server#3]
Hi,

I've set an alert using:
```
curl 'http://localhost:8091/api/SetAlert?token=abcdefghijklmnop' -X POST -H 'Content-Type: application/json'  -d '{"text": "This is a test"}'
```
It gets shown in the presentation. But `GetCPInfo` returns an empty `alert_text`:

```
curl -s 'http://localhost:8091/api/GetCPInfo?token=abcdefghijklmnop' -X POST -H 'Content-Type: application/json' -d '{}' |jq .
{
  "status": "ok",
  "data": {
    "text": "",
    "show": false,
    "display_ahead": false,
    "alert_text": "",
    "alert_show": false,
    "countdown_show": false,
    "countdown_time": 0,
    "stopwatch_show": false,
    "stopwatch_time": 0,
    "theme": -1,
    "countdown_font_relative_size": 250,
    "countdown_font_color": "FCFCFC",
    "stopwatch_font_color": "00FF00",
    "time_font_color": "FCFCFC",
    "display_clock_as_background": false,
    "display_clock_on_alert": false,
    "countdown_display_location": "FULLSCREEN",
    "display_clock_with_countdown_fullscreen": true,
    "display_vlc_player_remaining_time": false
  }
}
```
I try to query whether an alert is being shown, and since there's no `GetAlert` call, I was hoping to get the required info from `GetCPInfo`.

**Comment by holyrics** [comment]
Hi,

There are two alert components to the program.
The main window alert, which is displayed in the main (audience) projection.
And the alert from the so-called "communication panel", which is displayed on return screens.
To change the communication panel alert text (returned in `GetCPInfo`) the method is `SetAlertCommunicationPanel` (alias `SetAlertCP`).

Changing the communication panel alert text is also available in the `SetCommunicationPanelSettings` method (alias `SetCPSettings`)
which is the corresponding method of `GetCommunicationPanelInfo` (aliases: `GetCPInfo` and `GetCPSettings`)

**Comment by holyrics** [comment]
Oh, and I forgot to comment,
For some reason I forgot to add the GetAlert method to the documentation.

But it is available, you can call it to get the audience alert information, the parameters returned in `data` are `text` and `show`

I'll add it in the next documentation update, thanks!

**Comment by JeLuF** [comment]
Thanks, `GetAlert` works fine. Is there also a `GetCountdown` call?

**Comment by holyrics** [comment]
There is no specific method to get the main screen countdown.
But it is possible to do an indirect check.
consider "p" as the "data" field obtained from `GetCurrentPresentation`
```
request GetCurrentPresentation
-d '{ include_slides: true }'

response
{
  "status": "ok",
  "data": { ... }
}
```

```javascript
function extractCountdownTimeFromPresentation(p) {
  if (p == null) {
    return null;
  }
  if (p.type != 'unknown' && p.type != 'countdown') {
    return null;
  }
  if (p.slide_number != 1 || p.total_slides != 1) {
    return null;
  }
  if (p.slides == null) {
    return null;
  }
  var rows = p.slides[0].text.split("\n");
  if (rows.length != 2 && rows.length != 3) {
    return null;
  }
  var row = (rows.length == 2) ? rows[0] : rows[1];;
  var regex = /^[\d:.]*$/;
  return regex.test(row) ? row : null;
}
```

The function returns the string with the current countdown time, which can be M:SS, MM:SS or HH:MM:SS

Or returns null if the presentation is not a countdown

Observation:
I verified that for the countdown presentation type, currently the `type` returned is `unknown`, instead of `countdown`.
I will adjust it for the next update, so I put `unknown` and `countdown` in the example to be compatible with a future update.

I can also add information in the `date` field itself returned from `GetCurrentPresentation`, example: `p.time`, instead of trying to identify with split and number of slides as in the example above, because any future change in the structure of the displayed countdown in the program can make the example above break.

Finally, I saw that you started a repository to implement a bitfocus module for Holyrics.
Thanks!

I'm working on a program update scheduled for April, and in the next few days I'll start implementing things related to API Server.
Feel free if you want to follow more closely in the Holyrics Beta group on Telegram [https://holyrics.com.br/_beta/join.html](https://holyrics.com.br/_beta/join.html)
If you need to request any specific needs for the module you are implementing and test new implementations using the beta version of the program.

**Comment by JeLuF** [comment]
I'm making good progress on the module. I'm currently implementing the feedbacks. This is a mechanism in Companion to dynamically change buttons depending on the state of the controlled "device", so that for example the "Hide presentation" button can be grayed out when no presentation is active. 

`GetCurrentPresentation` returns the total number of slides and the slide currently being displayed. I tried to use this to gray out the `ActionNext` button at the end of the slide deck. Works fine for songs, but not for verses.

I send a list of references:
```
curl -s 'http://localhost:8091/api/ShowVerse?token=abcdefghijklmnop' -X POST -H 'Content-Type: application/json' -d '{ "references": "Rm 12:2  Gn 1:1-3  Ps 23"}' |jq .
{
  "status": "ok"
}
```
The `GetCurrentPresentation` result doesn't return the number of slides:
```
curl -s 'http://localhost:8091/api/GetCurrentPresentation?token=abcdefghijklmnop' -X POST -H 'Content-Type: application/json'  -d '{"include_slides": true}' |jq
{
  "status": "ok",
  "data": {
    "id": "45012002",
    "type": "verse",
    "name": "Rm 12:2"
  }
}
```
I guess this is because it's more difficult to compute the number of actual slides without computing each of them? For now, if the slide type is `verse`, I will not gray out the `ActionNext` button.

**Comment by holyrics** [comment]
I just saw it, it looks great!

Regarding the verses, when displaying a verse in the program (which is the default action) the forward and back action has no limit, in practice, the projection presentation is a slide with all the Bible verses.
That's why I didn't even think about adding this information.
But in this case it is really useful if the presentation of verses is a specific sequence informed by the user.
It is already noted to implement this return in `GetCurrentPresentation` for verse presentation

A note about requests

```javascript
var slide = JSON.parse(await this.do_command('GetCurrentPresentation', { include_slides: true }))
var alert = JSON.parse(await this.do_command('GetAlert'))
var f8    = JSON.parse(await this.do_command('GetF8'))
var f9    = JSON.parse(await this.do_command('GetF9'))
var f10   = JSON.parse(await this.do_command('GetF10'))
```

F8 F9 and F10 are exclusive, that is, no two will be activated at the same time.
You can use the `slide.data?.slide_type` information to check the status of F8, F9 and F10
```javascript
this.state['f8_active'] = slide.data?.slide_type == 'wallpaper'
this.state['f9_active'] = slide.data?.slide_type == 'blank'
this.state['f10_active'] = slide.data?.slide_type == 'black'
```

This will avoid having to make 5 requests to the looper.
At the moment this would not work for verse presentation, as like the slide information, the `slide_type` is also not returned, but I will add these fields to the return soon.

At the moment you can check the status as per the example above, and if the presentation type is `verse`, then you make individual requests for f8, f9 and f10

**Comment by JeLuF** [comment]
I got a repo on the bitfocus organization: https://github.com/bitfocus/companion-module-limagiran-holyrics
I've migrated the module to that repo.

● Is there a reason, why, when I use `right-click -> Script info`, filenames are enclosed in quotes (`"`), but IDs aren't? Makes it a bit more complicated when copy-pasting the file names to the companion. Unfortunately, Companion has no API exposed that I can use to update a dropdown when the user configures a button. I could only poll the Holyrics server every X seconds for all the texts, audios, videos, lyrics, etc. I'm not sure whether this is a good idea. Do you know how many assets your users typically manage?

● Is there a command to stop or pause `PlayAudio`?

● Using `PlayAudio`, I'm able to set the start/stop times, but the `volume` option has no effect:
```
{"file":"embeddings.mp3","settings":{"volume":0,"repeat":false,"start_time":"0", "stop_time":"5"}}
```
I tried different values, like `100`, `1`, `0.1`, `0` - but all sound the same. I can change the volume using the slider in the Holyrics application.

**Comment by holyrics** [comment]
• The lack of quotation marks is, in general, due to the type of id. When it is a number (long) it is without quotation marks, as theoretically it could be used without quotation marks.
But I've already realized that it's actually better to add quotation marks, even in numeric IDs, because they can be converted to floating point by javascript and the Holyrics API cannot identify the number correctly.
I will add quotation marks to all IDs, by default, because even if the numeric ID is "sent" as a string, the api will be able to identify it correctly, without any problems.
I don't have information about the number of media files, but the number of song lyrics, in general, is well distributed between 100 and 1000.
However, quantities greater than 1000 are quite common.
In fact, a loop to update this information is not ideal, especially because the program's media tabs accept subfolders, so users can organize files in different folders and subfolders, which would cause a need to make a recursive request to list all files.

If this is a demand from users when the module is available, we can check some alternative solution, but for now my suggestion would be to give priority to the favorites bar and the playlist (both lyrics and media).
The default use of the program is for the user to add to the playlist (on the right part of the program's main window) all the items he will use that day, and to the favorites bar, all the important items he needs quick access to. is easy.
What do you think?

• [MediaPlayerAction](https://github.com/holyrics/API-Server?#mediaplayeraction)
```
{  "action": "pause" }

play | pause | stop | next | previous
```

• Does the volume slide in the main window player change?
If yes, in practice, the volume parameter is ok.
What may be happening is the possible bug/incompatibility existing in VLC versions from v2.1+
If you are testing this command on Linux or OSX, this is the cause of the problem.
The player volume is changed before the media starts, however for versions of VLC 2.1+, the vlc module does not receive the volume change if the media has not been started (play), so the media is played at the previous volume.
This also happens with mute.
I will check a possible solution in Holyrics itself so that the volume change (or mute) call in the vlc module is redone as soon as the media is executed, when the vlc version is 2.1+
The only problem will be that the audio may play for a few thousandths of a second before the volume change (or mute) takes effect.

**Comment by JeLuF** [comment]
● That really sounds like a dropdown with all songs wouldn't work. 

I see that there are two playlists, one for lyrics, one for media. So the operator would need to know when to show the next song or media asset? 

In the API, I couldn't find any calls to go to the next playlist item. So if I'd wanted to go through the playlist song by song (without interacting with the Holyrics UI), I'd have to keep track in the companion module? I could have four buttons `Next song`, `Previous song`, `Next medium`, `Previous medium`. Would that make sense?

● `{  "action": "pause" }` How did I miss this? I thought I had searched the documentation for both `pause` and `stop`. Will add this.

● I'm on Windows at the moment.
>  Does the volume slide in the main window player change?

Not via the API. I can change it manually in the UI and it affects the playback volume.

**Comment by holyrics** [comment]
> I see that there are two playlists, one for lyrics, one for media. So the operator would need to know when to show the next song or media asset?

There are users who use only one of the lists, either song lyrics or media (the media list allows several types of items, including song lyrics), and there are users who use both lists simultaneously (per organization, perhaps).


> In the API, I couldn't find any calls to go to the next playlist item. So if I'd wanted to go through the playlist song by song (without interacting with the Holyrics UI), I'd have to keep track in the companion module? I could have four buttons `Next song`, `Previous song`, `Next medium`, `Previous medium`. Would that make sense?

Well, this issue of the next media item I find particularly complex, because of the way the Holyrics program works, and the possibility of the media list containing several different types of items, not every item is an item that generates a presentation on the screen.

I implemented a few versions ago option for user to set shortcut key to go to next item in music list and shortcut key to next item in media list.
As it is something that I initially added as a test to see what the result would be, I did not implement it in the api.
I can implement these two actions in the api.
Actually four, I can add the "previous" option as well.
But I need to create a checkbox list in the program interface for the user to define which item types will be valid to create the media playlist execution "queue".

Although it is possible to do this in the companion module itself, storing the ID of the last item played and playing the next item with `ShowLyrics {id: id}` (for song lyrics) or `MediaPlaylistAction {id: id}` (for playlist of media), perhaps it would be better to implement it natively in the Holyrics API itself.


> Not via the API. I can change it manually in the UI and it affects the playback volume.

I did a test here via the API and it really isn't working (I had only tested it with javascript within Holyrics, via jslib, I didn't imagine that via the network it would have a different result).
I discovered that the problem is that in the internal json conversions the volume is being saved in a string as a floating point, and when trying to convert the string with a dot to int it is throwing an exception.
I'll fix this later, but for now you can send the volume as a string which also solves the problem.

**Comment by JeLuF** [comment]
Hi, the module has been accepted by the Bitfocus devs and is included since today's _Beta_ version `3.3.0+6909-main-04c4b0c1`. If you want to have a look, Companion has a streamdeck emulator, so that the module can be tested even without a streamdeck.

**Comment by holyrics** [comment]
Hi!
I did some tests and it worked well!
I had never used Companion (despite having an idea of how it works) and it was still easy to understand how it works and configure the actions.
Thank you very much! God blesses.

I have some considerations, if you allow me, and there are also changes to the API Server that I made in the v2.22.0 update of the program released today that I can explain to you, as I haven't updated the documentation yet.

However, there are many different topics that I would like to comment on, would you prefer me to write them here or can I create different issues in the bitfocus/companion-module-limagiran-holyrics repository for better organization?

Thank you again!

**Comment by JeLuF** [comment]
Hi, I think the bitfocus/companion-module-limagiran-holyrics issue tracker would make most sense.

Btw, I'm not part of bitfocus. I just noticed the feature request on their request tracker and thought that this would be an approriate little project for the Easter weekend.

**Comment by holyrics** [comment]
> Hi, I think the bitfocus/companion-module-limagiran-holyrics issue tracker would make most sense.
> 
> Btw, I'm not part of bitfocus. I just noticed the feature request on their request tracker and thought that this would be an approriate little project for the Easter weekend.

Of course!
Recently a user of the program got in touch asking about the possibility of adding a Holyrics companion module, I explained that at the moment I could not work on that specifically, and I explained that even creating a Holyrics module would not need to be done specifically by me, that other developer(s) could create this module just based on the Holyrics API-Server documentation.
Soon after, this person (I believe it was the same person) opened a request on the companion's github and then everything happened.
I'm really happy, and I'm grateful.
